import { addDays } from './addDays'
import { getAddress, formatAddress } from './address'
import { breakpoints, device } from './breakpoints'
import { setCookie, getCookie, removeCookie } from './cookies'
import {
  getLastTenDays,
  getLastTenDaysValues,
  getTopFive,
  objectMap,
} from './dashboard'
import {
  trendingTypes,
  dataView,
  filterDict,
  nationalAveragesDict,
  addressDict,
} from './dict'
import {
  getPercentage,
  slugify,
  thousands,
  titleCase,
  getInitials,
  validateEmail,
  checkPath,
  noAuthRequired,
  deslugify,
  getGraphData,
  camelCaseToText,
  getAlertTime,
  isObjEmpty,
  renameAllKeysInArr,
  checkPermissions,
  renameKeys,
  removeFromString,
  isNegative,
  mergeArraysToObject,
  arrayEquals,
  matchRoute,
  useIsMount,
} from './helperFn'
import { noAuth, authRedirect } from './routes'
import { states } from './states'

export {
  authRedirect,
  dataView,
  addressDict,
  useIsMount,
  matchRoute,
  device,
  renameKeys,
  renameAllKeysInArr,
  getGraphData,
  states,
  breakpoints,
  titleCase,
  validateEmail,
  removeFromString,
  noAuthRequired,
  getLastTenDays,
  nationalAveragesDict,
  getLastTenDaysValues,
  arrayEquals,
  formatAddress,
  mergeArraysToObject,
  getTopFive,
  objectMap,
  getInitials,
  noAuth,
  checkPath,
  trendingTypes,
  thousands,
  slugify,
  getPercentage,
  addDays,
  getAddress,
  deslugify,
  setCookie,
  getCookie,
  removeCookie,
  filterDict,
  camelCaseToText,
  isObjEmpty,
  checkPermissions,
  getAlertTime,
  isNegative,
}
